[2024-07-27T00:00:16.675+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_demo.get_metrics scheduled__2024-07-26T00:00:00+00:00 [queued]>
[2024-07-27T00:00:16.684+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_demo.get_metrics scheduled__2024-07-26T00:00:00+00:00 [queued]>
[2024-07-27T00:00:16.685+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-27T00:00:16.712+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_metrics> on 2024-07-26 00:00:00+00:00
[2024-07-27T00:00:16.721+0000] {standard_task_runner.py:60} INFO - Started process 18555 to run task
[2024-07-27T00:00:16.724+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_demo', 'get_metrics', 'scheduled__2024-07-26T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline3.py', '--cfg-path', '/tmp/tmp09umtg67']
[2024-07-27T00:00:16.727+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask get_metrics
[2024-07-27T00:00:16.783+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_demo.get_metrics scheduled__2024-07-26T00:00:00+00:00 [running]> on host 6032203f0166
[2024-07-27T00:00:16.860+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline_demo' AIRFLOW_CTX_TASK_ID='get_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-07-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-26T00:00:00+00:00'
[2024-07-27T00:00:16.862+0000] {logging_mixin.py:188} INFO - --- Inside get_metrics component ---
[2024-07-27T00:00:16.871+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline3.py", line 89, in get_metrics
    entropy = log_loss(y_test, y_pred_prob)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 2844, in log_loss
    y_pred = check_array(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 915, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 380, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: could not convert string to float: 'Iris-versicolor'
[2024-07-27T00:00:16.881+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_demo, task_id=get_metrics, execution_date=20240726T000000, start_date=20240727T000016, end_date=20240727T000016
[2024-07-27T00:00:16.891+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 55 for task get_metrics (could not convert string to float: 'Iris-versicolor'; 18555)
[2024-07-27T00:00:16.937+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-27T00:00:16.959+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
